---
output:
  word_document:
    reference_docx: report_HR_style_template.docx
---

```{r info, include=F}

#This script reads in data and tables directly from www.stockassessment.org

#Remember to save the reference docx for styles the same place at the rmd script - input_tables_SAM_word_style.docx


```


```{r setup, include=FALSE}
# devtools::install_github("fishfollower/SAM/stockassessment", ref="multi")

path_root <-
  "C:/Users/kibi/OneDrive - Danmarks Tekniske Universitet/stock_coord_work/her.27.20-24/2026_her.27.20-24_RDBES_combined/"

knitr::opts_knit$set(root.dir = path_root)

library(pander)
library(stockassessment)
library(htmlTable)
library(dplyr)
library(reshape2)
library(rvest)
library(data.table)
library(flextable)

options(scipen=999)

# Single fleet
dir_dat <-
  "https://www.stockassessment.org/datadisk/stockassessment/userdirs/user295/WBSS_HAWG_2026/data/" #input data directly from www.stockassessment.org
dir_fig <-
  "https://www.stockassessment.org/datadisk/stockassessment/userdirs/user295/WBSS_HAWG_2026/res/" #tables directly from www.stockassessment.org
fig_prefix<-"xxx-00-00.00.00_" #Prefix for figures at www.stockassessment.org

panderOptions("table.style", "rmarkdown")
panderOptions("table.alignment.default", "right")
panderOptions('table.split.table', Inf)

knitr::opts_chunk$set(echo=F, warning=F, message=F)

set_flextable_defaults(
  font.family = "Calibri",
  font.size = 7.5,
  padding.bottom = 0,
  padding.top = 0
)


```

**TABLE 3.9.1 - WESTERN BALTIC SPRING SPAWNING HERRING**\
*Single fleet*\
Input table for short term predictions

Done by Vanessa

```{r, ft.align="left"}

t37 <- as.data.frame(read_html(paste(dir_fig, fig_prefix, "tabX1.html", sep="")) %>% html_table(fill=TRUE))

t37 <- t37[c(3, 5:(nrow(t37)-1)),]

colnames(t37)<-unlist(t37[1, ], use.names = FALSE)

t37.1<-t37[-1,]
row.names(t37.1)<-NULL

t37.2 <- t(t37.1[-1])
colnames(t37.2) <- t37.1[, 1]

t37.2 <- data.table(t37.2, keep.rownames = "value")


t <- flextable(t37.2) %>%
  set_table_properties(width = 1, layout = "autofit") %>%
  bold(part = "header") %>%
  padding(padding.bottom = 0, part = "all") %>%
  padding(padding.top = 0, part = "all") %>%
  bg(bg = "#B7D1C3", part = "header") %>%
  border_inner_h(part = "all") %>%
  set_caption(
    caption = paste0(
      "TABLE 3.9.2 - WESTERN BALTIC SPRING SPAWNING HERRING. Single fleet. Forecast table. ICES MSY approach: AR with F=0 below Blim"
    ),
    style = "Table Caption"
  ) %>%
  colformat_num(big.mark = "", na_str = "-")

t

```

```{r, ft.align="left"}
t37 <- as.data.frame(read_html(paste(dir_fig, fig_prefix, "tabX2.html", sep="")) %>% html_table(fill=TRUE))

t37 <- t37[c(3, 5:(nrow(t37)-1)),]

colnames(t37)<-unlist(t37[1, ], use.names = FALSE)

t37.1<-t37[-1,]
row.names(t37.1)<-NULL

t37.2 <- t(t37.1[-1])
colnames(t37.2) <- t37.1[, 1]

t37.2 <- data.table(t37.2, keep.rownames = "value")

t <- flextable(t37.2) %>%
  set_table_properties(width = 1, layout = "autofit") %>%
  bold(part = "header") %>%
  padding(padding.bottom = 0, part = "all") %>%
  padding(padding.top = 0, part = "all") %>%
  bg(bg = "#B7D1C3", part = "header") %>%
  border_inner_h(part = "all") %>%
  set_caption(
    caption = paste0(
      "TABLE 3.9.3 - WESTERN BALTIC SPRING SPAWNING HERRING. Single fleet. Forecast table. EU Baltic Sea multiannual plan (MAP): F=Fmsy*SSB2026/MSYBtrigger."
    ),
    style = "Table Caption"
  ) %>%
  colformat_num(big.mark = "", na_str = "-")

t
```

```{r, ft.align = "left"}
t37 <- as.data.frame(read_html(paste(dir_fig, fig_prefix, "tabX3.html", sep="")) %>% html_table(fill=TRUE))

t37 <- t37[c(3, 5:(nrow(t37)-1)),]

colnames(t37)<-unlist(t37[1, ], use.names = FALSE)

t37.1<-t37[-1,]
row.names(t37.1)<-NULL

t37.2 <- t(t37.1[-1])
colnames(t37.2) <- t37.1[, 1]

t37.2 <- data.table(t37.2, keep.rownames = "value")


t <- flextable(t37.2) %>%
  set_table_properties(width = 1, layout = "autofit") %>%
  bold(part = "header") %>%
  padding(padding.bottom = 0, part = "all") %>%
  padding(padding.top = 0, part = "all") %>%
  bg(bg = "#B7D1C3", part = "header") %>%
  border_inner_h(part = "all") %>%
  set_caption(
    caption = paste0(
      "TABLE 3.9.4 - WESTERN BALTIC SPRING SPAWNING HERRING. Single fleet. Forecast table. F=FMSY=Fpa=0.05"
    ),
    style = "Table Caption"
  ) %>%
  colformat_num(big.mark = "", na_str = "-")

t
```

```{r, ft.align = "left"}
t37 <- as.data.frame(read_html(paste(dir_fig, fig_prefix, "tabX4.html", sep="")) %>% html_table(fill=TRUE))

t37 <- t37[c(3, 5:(nrow(t37)-1)),]

colnames(t37)<-unlist(t37[1, ], use.names = FALSE)

t37.1<-t37[-1,]
row.names(t37.1)<-NULL

t37.2 <- t(t37.1[-1])
colnames(t37.2) <- t37.1[, 1]

t37.2 <- data.table(t37.2, keep.rownames = "value")

t <- flextable(t37.2) %>%
  set_table_properties(width = 1, layout = "autofit") %>%
  bold(part = "header") %>%
  padding(padding.bottom = 0, part = "all") %>%
  padding(padding.top = 0, part = "all") %>%
  bg(bg = "#B7D1C3", part = "header") %>%
  border_inner_h(part = "all") %>%
  set_caption(
    caption = paste0(
      "TABLE 3.9.5 - WESTERN BALTIC SPRING SPAWNING HERRING. Single fleet. Forecast table. F=F2026=0.008"
    ),
    style = "Table Caption"
  ) %>%
  colformat_num(big.mark = "", na_str = "-")

t
```


```{r, ft.align = "left"}
t37 <- as.data.frame(read_html(paste(dir_fig, fig_prefix, "tabX5.html", sep="")) %>% html_table(fill=TRUE))

t37 <- t37[c(3, 5:(nrow(t37)-1)),]

colnames(t37)<-unlist(t37[1, ], use.names = FALSE)

t37.1<-t37[-1,]
row.names(t37.1)<-NULL

t37.2 <- t(t37.1[-1])
colnames(t37.2) <- t37.1[, 1]

t37.2 <- data.table(t37.2, keep.rownames = "value")

t <- flextable(t37.2) %>%
  set_table_properties(width = 1, layout = "autofit") %>%
  bold(part = "header") %>%
  padding(padding.bottom = 0, part = "all") %>%
  padding(padding.top = 0, part = "all") %>%
  bg(bg = "#B7D1C3", part = "header") %>%
  border_inner_h(part = "all") %>%
  set_caption(
    caption = paste0(
      "TABLE 3.9.6 - WESTERN BALTIC SPRING SPAWNING HERRING. Single fleet. Forecast table. F=0.005"
    ),
    style = "Table Caption"
  ) %>%
  colformat_num(big.mark = "", na_str = "-")

t
```

```{r, ft.align = "left"}
t37 <- as.data.frame(read_html(paste(dir_fig, fig_prefix, "tabX6.html", sep="")) %>% html_table(fill=TRUE))

t37 <- t37[c(3, 5:(nrow(t37)-1)),]

colnames(t37)<-unlist(t37[1, ], use.names = FALSE)

t37.1<-t37[-1,]
row.names(t37.1)<-NULL

t37.2 <- t(t37.1[-1])
colnames(t37.2) <- t37.1[, 1]

t37.2 <- data.table(t37.2, keep.rownames = "value")

t <- flextable(t37.2) %>%
  set_table_properties(width = 1, layout = "autofit") %>%
  bold(part = "header") %>%
  padding(padding.bottom = 0, part = "all") %>%
  padding(padding.top = 0, part = "all") %>%
  bg(bg = "#B7D1C3", part = "header") %>%
  border_inner_h(part = "all") %>%
  set_caption(
    caption = paste0(
      "TABLE 3.9.7 - WESTERN BALTIC SPRING SPAWNING HERRING. Single fleet. Forecast table. F=0.01"
    ),
    style = "Table Caption"
  ) %>%
  colformat_num(big.mark = "", na_str = "-")

t
```

```{r, ft.align = "left"}
t37 <- as.data.frame(read_html(paste(dir_fig, fig_prefix, "tabX7.html", sep="")) %>% html_table(fill=TRUE))

t37 <- t37[c(3, 5:(nrow(t37)-1)),]

colnames(t37)<-unlist(t37[1, ], use.names = FALSE)

t37.1<-t37[-1,]
row.names(t37.1)<-NULL

t37.2 <- t(t37.1[-1])
colnames(t37.2) <- t37.1[, 1]

t37.2 <- data.table(t37.2, keep.rownames = "value")

t <- flextable(t37.2) %>%
  set_table_properties(width = 1, layout = "autofit") %>%
  bold(part = "header") %>%
  padding(padding.bottom = 0, part = "all") %>%
  padding(padding.top = 0, part = "all") %>%
  bg(bg = "#B7D1C3", part = "header") %>%
  border_inner_h(part = "all") %>%
  set_caption(
    caption = paste0(
      "TABLE 3.9.8 - WESTERN BALTIC SPRING SPAWNING HERRING. Single fleet. Forecast table. F=0.02"
    ),
    style = "Table Caption"
  ) %>%
  colformat_num(big.mark = "", na_str = "-")

t
```

```{r, ft.align = "left"}
t37 <- as.data.frame(read_html(paste(dir_fig, fig_prefix, "tabX8.html", sep="")) %>% html_table(fill=TRUE))

t37 <- t37[c(3, 5:(nrow(t37)-1)),]

colnames(t37)<-unlist(t37[1, ], use.names = FALSE)

t37.1<-t37[-1,]
row.names(t37.1)<-NULL

t37.2 <- t(t37.1[-1])
colnames(t37.2) <- t37.1[, 1]

t37.2 <- data.table(t37.2, keep.rownames = "value")

t <- flextable(t37.2) %>%
  set_table_properties(width = 1, layout = "autofit") %>%
  bold(part = "header") %>%
  padding(padding.bottom = 0, part = "all") %>%
  padding(padding.top = 0, part = "all") %>%
  bg(bg = "#B7D1C3", part = "header") %>%
  border_inner_h(part = "all") %>%
  set_caption(
    caption = paste0(
      "TABLE 3.9.9 - WESTERN BALTIC SPRING SPAWNING HERRING. Single fleet. Forecast table. F=0.03"
    ),
    style = "Table Caption"
  ) %>%
  colformat_num(big.mark = "", na_str = "-")

t
```


```{r, ft.align = "left"}
t37 <- as.data.frame(read_html(paste(dir_fig, fig_prefix, "tabX9.html", sep="")) %>% html_table(fill=TRUE))

t37 <- t37[c(3, 5:(nrow(t37)-1)),]

colnames(t37)<-unlist(t37[1, ], use.names = FALSE)

t37.1<-t37[-1,]
row.names(t37.1)<-NULL

t37.2 <- t(t37.1[-1])
colnames(t37.2) <- t37.1[, 1]

t37.2 <- data.table(t37.2, keep.rownames = "value")

t <- flextable(t37.2) %>%
  set_table_properties(width = 1, layout = "autofit") %>%
  bold(part = "header") %>%
  padding(padding.bottom = 0, part = "all") %>%
  padding(padding.top = 0, part = "all") %>%
  bg(bg = "#B7D1C3", part = "header") %>%
  border_inner_h(part = "all") %>%
  set_caption(
    caption = paste0(
      "TABLE 3.9.10 - WESTERN BALTIC SPRING SPAWNING HERRING. Single fleet. Forecast table. Constant intermediate year catch = 1905 t"
    ),
    style = "Table Caption"
  ) %>%
  colformat_num(big.mark = "", na_str = "-")

t
```



```{r, ft.align = "left"}
t37 <- as.data.frame(read_html(paste(dir_fig, fig_prefix, "tabProb.html", sep="")) %>% html_table(fill=TRUE))

t37 <- t37[c(3, 5:(nrow(t37)-1)),]

colnames(t37)<-unlist(t37[1, ], use.names = FALSE)

t37.1<-t37[-1,]
row.names(t37.1)<-NULL

colnames(t37.1) <- c("Scenario", names(t37.1)[c(2:3)])

t37.1 <- data.table(t37.1, keep.rownames = "value")

t <- flextable(t37.1) %>%
  set_table_properties(width = 1, layout = "autofit") %>%
  bold(part = "header") %>%
  padding(padding.bottom = 0, part = "all") %>%
  padding(padding.top = 0, part = "all") %>%
  bg(bg = "#B7D1C3", part = "header") %>%
  border_inner_h(part = "all") %>%
  set_caption(
    caption = paste0(
      "TABLE 3.9.11 - WESTERN BALTIC SPRING SPAWNING HERRING. Single fleet. Forecast table. Probability of SSB being below Blim in two relevant forecast years"
    ),
    style = "Table Caption"
  ) %>%
  colformat_num(big.mark = "", na_str = "-")

t
```
